server:
  port: 9090
  
#spring:
#  security:
#    oauth2:
#      authorizationserver:
#        issuer: http://localhost:9090/oauth/token
#        client:
#          articles-client:
#            registration:
#              client-id: articles-client
#              client-secret: "{noop}secret"
#              client-name: Articles Client
#              client-authentication-methods:
#                - client_secret_basic
#              authorization-grant-types:
#                - authorization_code
#                - refresh_token
#                - check_token
#                - password
#              redirect-uris:
#                - http://127.0.0.1:8080/login/oauth2/code/articles-client-oidc
#                - http://127.0.0.1:8080/authorized
#              scopes:
#                - openid
#                - articles.read